### PR TITLE
can handle multiselect optionsets now

### PR DESCRIPTION
**Pull request by cyco77**
in addition I removed the language check. Now foreign languages will be generated too

### CODE REVIEW

**Comment by cyco77** [comment]
hmm... made a mistake... forgot to create new branch on my side for the new feature... now it's mixed with my other changes... if it's ok for you, I would finish version one of metadata explorer

**Comment by Power-Maverick** [comment]
Yes. Separate PR for feature is better for review and test as well. Take your own time 😊
Thanks for improving the tool.

**Comment by cyco77** [comment]
@Power-Maverick it would be great if you could check this version. In my eyes it's still not complete, but this version gives some additional value to the users. Im the next couple of days, I will extend this feature

**Comment by Power-Maverick** [comment]
@cyco77 can you provide a list all the features you have added or upgraded; so that I don't have to perform all the testing for this PR. I know I have to build automated test cases but maybe for the future.

**Review by Power-Maverick — APPROVED** [review]

**Comment by cyco77** [comment]
@Power-Maverick
Here is a list of changes I made:

code generation:
- state & status code
- multi optionset values

meta data explorer
- entity list added
- entity detail view extended
- table sorting added / improved

**Pull request merged**
